### ISSUE TITLE
How was the cell labeling achieved?

### ISSUE THREAD

**Issue by friedue** [AmandaKedaigle/BrainOrganoidsReproducibility#1]
Hi Amanda,

thanks for providing the code to the Nature publication about Brain Organoid Reproducibility. 
I was curious to see how you attributed the fairly definitive and specific cell type labels that are used throughout the manuscript (e.g. "CPNs", "Cajal-Retzius") etc.

In the `downstream_analyses` script it seems as if the labels just magically appeared --  is that because there was a manual labeling step involved?

```
#Calculate DEGs per cluster. Use this list to assign a cell type to each cluster
seur <- SetAllIdent(seur, id=clustcolname)
seur.markers <- FindAllMarkers(object = seur, only.pos = T, test.use = "MAST", logfc.threshold = 0.25)
write.table(seur.markers, file="markerLists.txt")

# tsne colored by cell type
# by now, should have ID'd cell types from DEG lists, and added a "CellType" column to the seur metadata
seur <- SetAllIdent(seur,id="CellType")
seur@ident = factor(seur@ident, levels= c("Immature PNs","Immature CPNs","CPNs","Immature CFuPNs","CFuPNs", "IPCs/Immature PNs", "IPCs",
                                          "Immature Interneurons","Ventral Precursors","Astroglia", "RG","oRG", 
                                          "Cycling","oRG/Astroglia","Unknown","Cajal-Retzius"))
```

**Comment by AmandaKedaigle** [comment]
Hello!
Yes, you're correct that cell types were assigned manually. After clustering and calculating upregulated genes for each cluster as shown in the code, identities for each cluster were determined by comparing upregulated genes to known marker genes for cell types (very few examples of marker genes for each cell type can be seen Ext. Data Fig 2). Once we had a label for each cluster, it was stored in the metadata slot "CellType" in the Seurat object.

Hope that helps!
