### ISSUE TITLE
need help for the cell types

### ISSUE THREAD

**Issue by JianmeiZhong** [AmandaKedaigle/BrainOrganoidsReproducibility#2]
Hi, 
 Thanks for your detailed codes that i can understand the workflow smoothly.  But with the limited computation performance of my laptop and the thousands-of-megabytes size of data,  It's not so easy to get through. Can i request the meta data file with corresponding relationships between barcodes and cell types , if it's not too much trouble ?

Best Regards

**Comment by AmandaKedaigle** [comment]
Hi - this shouldn't be a problem. Can you email me at akedaigl @ broadinstitute.com and I can pass it along. Thanks!

Amanda

**Comment by AmandaKedaigle** [comment]
Actually, even easier - you can access the metadata from this page on the Single Cell Portal under the Download tab: https://singlecell.broadinstitute.org/single_cell/study/SCP282/reproducible-brain-organoids
