### ISSUE TITLE
cellranger process single-end scRNAseq

### ISSUE THREAD

**Issue by BenxiaHu** [AmandaKedaigle/BrainOrganoidsReproducibility#3]
Hello,
   did you used cellranger to process single-end single-cell RNA-seq?

**Comment by AmandaKedaigle** [comment]
We used cellranger, yes! This is 10X sequencing, which is paired end - read 1 contains the 10x barcode and UMI while read 2 contains the sequenced cDNA fragment

**Comment by BenxiaHu** [comment]
thanks. 
the deposited scRNA-seq in GEO are single-end reads (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE129519). 
would you like to double check them?
